
--  V4.2 -----------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis) VALUES
--'Fullmetal Alchemist' - 13 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Aquel que desafía al Sol', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'El cuerpo del condenado', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Madre', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Transmutación de amor', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        '¡Corre! Autómata', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'El examen de calificación para Alquimista Estatal', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'La noche en que la quimera lloró', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'La Piedra Filosofal', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Un reloj de plata para el perro de los militares', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Psiren, la ladrona', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Los otros hermanos Elric - Primera parte', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Los otros hermanos Elric - Segunda parte', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Fuego vs. Acero', 13, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist' - 12 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'El brazo derecho de la destrucción', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La masacre de Ishval', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Pérdidas', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La casa donde espera la familia', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La nota de Marcoh', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La verdad detrás de la verdad', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'El alma del guardián', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Brillo Carmesí', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Humano creado', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Corazón de acero', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Recuerdos implantados', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Ceremonia de despedida', 12, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist' - 16 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Su razón', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Maestro', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Uno es todo, todo es uno', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Niño inocente', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Asalto al Cuartel General del Sur', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Pecado', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El profundo bosque de Dante', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Al secuestrado', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Teoría de la avaricia', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Reunión de los Caídos', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El Pecador interno', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El Alquimista de Fuego, el Teniente Soltero y el Misterio del Almacén 13', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Con el fluir del río', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Guerra Civil del Este', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'La Cicatriz', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Madre Santa', 16, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist' - 10 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Su nombre es desconocido', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'El perro callejero', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Hohenheim de la Luz', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Alma corrupta', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Transmutación Humana', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Sellando a los homúnculos', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Adiós', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'El otro lado de la Puerta', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Muerte', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Munich 1921', 10, 'Lorem ipsum dolor sit amet')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis) VALUES
--'Fullmetal Alchemist Brotherhood' - 14 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El Alquimista de Acero', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El día del inicio', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La ciudad de la herejía', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La angustia de un Alquimista', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Lluvia de trizteza', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El camino hacia la esperanza', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La verdad oculta', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Investigando el Laboratorio número 5', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Sentimientos creados', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Cada destino', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Milagro en Rush Valley', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Uno es todo, y todo es uno', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Las bestias de Dublith', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Aquellos que acechan bajo la tierra', 14, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Emisario del Este', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Pasos de un camarada de guerra', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Llamas serenas', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'En la palma de un humano arrogante', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La muerte del inmortal', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Padre frente a la tumba', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'El progreso del tonto', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Espaldas distantes', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La chica de la guerra', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Dentro del estómago', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La puerta de la oscuridad', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Reunión', 12, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Banquete en la grieta', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Padre', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La lucha del tonto', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La campaña de aniquilación de Ishbal', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La promesa hecha por 520 Cenz', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'El hijo del Führer', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La muralla del norte de Briggs', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La Reina de Hielo', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La forma de este país', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Retrato de familia', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'El homúnculo original', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Conflicto en Baschool', 12, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Soñar despierto', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La criatura dentro del frasco', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Infierno', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Señales de un contraataque', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La mordedura de una hormiga', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Una recuperación completa', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'El día prometido', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La sombra cautelosa', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Mensajero de la oscuridad', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Un juramento hecho bajo tierra', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'El amor de un padre y un hijo', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Agitación en Central', 12, 'Lorem ipsum dolor sit amet'),


--'Fullmetal Alchemist Brotherhood' - 14 episodios 5 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Ejército inmortal', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El poder de todos', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Las llamas de la venganza', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Detrás de las llamas', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'La manera de vivir de los adultos', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El regreso del Führer', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Descanso Eterno', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Sacrificios humanos', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Luz perdida', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El ojo del cielo, la puerta de la Tierra', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Aquel que se tragó a Dios', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Contraataque violento', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El otro lado de la puerta', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El final del viaje', 14, 'Lorem ipsum dolor sit amet')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis) VALUES
--'Haikyuu' - 25 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El Fin y el Comienzo', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Club de Voleibol de la Preparatoria Karasuno', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El aliado más fuerte', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'La vista desde la cima', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El nerviosismo de un cobarde', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Un equipo interesante', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Contra el Gran Rey', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Aquel al que llaman estrella', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Un pase para la estrella', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Anhelo', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Decisión', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'La reunión de gatos y cuervos', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Rivales', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Oponentes formidables', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Renacimiento', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Ganadores y Perdedores', 16, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El Muro de Acero', 17, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Cubriendo sus espaldas', 18, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Directores', 19, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Toru Oikawa no es un genio', 20, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Las verdaderas habilidades del senpai', 21, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Evolución', 22, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El punto que cambia la corriente', 23, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Retirando al rey solitario', 24, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El tercer día', 25, 'Lorem ipsum dolor sit amet'),


--'Haikyuu' - 25 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        '¡Vamos a Tokyo!', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Luz Solar Directa', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Poblador B', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Estrella Central', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Codicia', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Ritmo', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Salida de la luna', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Héroe ilusorio', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'vs Un paraguas', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Engranajes', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Arriba', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        '¡Empiezan los partidos!', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Un poder simple y puro', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Aún en crecimiento', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Un lugar para jugar', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Siguiente', 16, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'La batalla sin fuerza de voluntad', 17, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Los perdedores', 18, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El Muro de Acero puede reconstruirse una y otra vez', 19, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Eliminando', 20, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El Destructor', 21, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'La pelea del antiguo cobarde', 22, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Equipo', 23, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El interruptor del límite absoluto', 24, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Declaración de guerra', 25, 'Lorem ipsum dolor sit amet'),


--'Haikyuu' - 10 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Saludos', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La amenaza del zurdo', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'GUESS-MONSTER', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La aureola que rodea la luna', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Individual vs Números', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La reacción química de los encuentros', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Obsesión', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Un tipo molesto', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Idiotas del voleibol', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La batalla de conceptos', 10, 'Lorem ipsum dolor sit amet'),


--'Haikyuu' - 25 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Presentaciones', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Perdido', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Punto de vista', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Tomarlo con calma', 4, 'Lorem ipsum dolor sit amet'),91aad460-d3f7-4c9e-ac5f-5c547c8e0311
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Hambre', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Mejoras', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Regreso', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Retador', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Una noche para todos', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Frente de batalla', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Una oportunidad de conectar', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Vívido', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El segundo día', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Ritmo', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Encontrar', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Corazón Roto', 16, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Gatos vs Monos', 17, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Trampa', 18, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El retador más fuerte', 19, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Líder', 20, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Héroe', 21, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Clavija', 22, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El nacimiento del rey silencioso', 23, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El festín de los monstruos', 24, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Tierra prometida', 25, 'Lorem ipsum dolor sit amet')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis) VALUES
--'Hanako-kun' - 12 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 1: Hanako-san de los Baños', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 2: Yousei-san', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 3: Las Escaleras Misaki, Parte 1', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 3: Las Escaleras Misaki, Parte 2', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 5: El Árbol de la Confesión', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 6: La Biblioteca de las 4 en Punto', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 7: Donas', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 8: Mitsuba', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 9: La Fiesta del te', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 10: El Infierno de los Espejos, Parte 1', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 10: El Infierno de los Espejos, Parte 2', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 12: La sirenita', 12, 'Lorem ipsum dolor sit amet 2')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis) VALUES
--'Cardcaptor Sakura' - 35 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el misterioso libro mágico', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La preciosa amiga de Sakura', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La primera cita de Sakura', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Agotador Domingo de Sakura', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, el Panda y la Tienda Maravillosa', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y los Recuerdos de su Madre', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Primera Batalla de Sakura contra un Misterioso Ladrón', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Rival de Sakura', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Broche Misterioso', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Campeonato y las Flores', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Tomoyo y la Gran Mansión', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Día Interminable de Sakura', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Elefante en la Competición de Fuerza', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Touya y la Cenicienta', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Gran Pelea de Sakura y Kero', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Arcoiris del Recuerdo', 16, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Terrorífica Prueba de Valor de Sakura', 17, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Yukito y la Feria de Verano', 18, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y los deberes del Verano', 19, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Nueva Enemiga de Sakura', 20, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Larga Carrera de Maratón de Sakura', 21, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y su Amable Padre', 22, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Tomoyo y una Hermosa Canción', 23, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Pequeña Gran Aventura de Sakura', 24, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la otra Sakura', 25, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y su Bellísima Profesora', 26, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Templo de Los Recuerdos', 27, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y sus Cartas Mágicas', 28, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Repostería', 29, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Carta Herida', 30, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Libro sin Nombre', 31, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Syaoran y Kero', 32, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Carta de Hielo', 33, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Yukito y la Luna Llena', 34, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Que maravilla de Navidad', 35, 'Lorem ipsum dolor sit amet'),


--'Cardcaptor Sakura' - 11 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Yukito y el Nuevo Curso Escolar', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y La Pérdida de Voz De Tomoyo', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y La Aventura De Coger Fresas', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Día de Fiebre y Mareos', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Sueño', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Syaoran y el Mar de Arena', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Festival de las Artes', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y la Despedida de Meilin', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Kero y la Misteriosa Profesora', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y la Última Carta de Clow', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Juicio Final', 11, 'Lorem ipsum dolor sit amet'),


--'Cardcaptor Sakura' - 24 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Misterioso Estudiante Nuevo', 1, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Despertar de la Llave Estrella', 2, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Piano Peligroso', 3, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Hilo Invisible', 4, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el abrazo del peluche', 5, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Aviso de las Ovejas', 6, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Bicicleta Asustada', 7, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Calendario de los Recuerdos', 8, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura en el País de las Maravillas', 9, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Kero y la Merienda', 10, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Ascensor', 11, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Doble Problema', 12, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Tomoyo y la Trampa de la Pelota', 13, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y una Querida Amiga', 14, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, la Carta y los Regalos', 15, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Extraña Predicción', 16, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, la Piscina y la Ola Gigante', 17, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Clase de Esquí', 18, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Yukito y el Poder de la Desaparición', 19, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'La Persona que más le Gusta a Sakura', 20, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Templo Tsukimine', 21, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, el Pasado y el Amo Clow', 22, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura se Encuentra con el Amo Clow', 23, 'Lorem ipsum dolor sit amet'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y sus Verdaderos Sentimientos', 24, 'Lorem ipsum dolor sit amet')
;









--'Fullmetal Alchemist Brotherhood' - 10 episodios 1 temporada
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 1, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 2, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 3, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 4, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 5, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 6, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 7, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 8, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 9, 'Lorem ipsum dolor sit amet'),
--    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal') AND num=1),
--        '', 10, 'Lorem ipsum dolor sit amet'),