
--  V4.2 -----------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis, link) VALUES
--'Fullmetal Alchemist' - 13 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Aquel que desafía al Sol', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/aHIy3bqY#ABJwnQCH9a22VScr9DVhLgDBmS8ACIWytqhuk_RN_jA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'El cuerpo del condenado', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7CJDgY5C#APYC5gAyQU0Hgof5l7fIwACvoUwAXNlHByQLT5dS8Eo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Madre', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6PAVSK4A#AC8WBwCcLHrrVEMpSZ9sLgDrdiIAkJjt68flT0l3cTw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Transmutación de amor', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/GThQ3CqD#ADeKtwDNbh2hLuks78uitQC_U7cAFN_BoVXWge8bRDU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        '¡Corre! Autómata', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DSxjgBrJ#AD_xZgAFBXFZ-Egaelrl9wAGEgMAxWmoWVOdoXqF7ms'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'El examen de calificación para Alquimista Estatal', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DeoigTzY#AJLmqgByK_zDSKFOZPOxAQD04c0A6mfSw0WvQWRUU6k'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'La noche en que la quimera lloró', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7bwwQTDK#AOrmigA24Fph0DW2wu4aFgAzYu8A-sRaYXvHYML4KC4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'La Piedra Filosofal', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/OKYB1JDK#AJlbFAAXRn8Z2Yj2pfHGGQCt5xkAsojwGeh-laVeeuM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Un reloj de plata para el perro de los militares', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/2W5R1AwB#AA_lQgBVHZ_XOJs8FvyEbQAiudYA0ASw12EnHRYeb38'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Psiren, la ladrona', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/PGpnFAJA#AATDpwBzAaEjJ28cwk375ABafzgAlcF9I4Qi0cIljRw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Los otros hermanos Elric - Primera parte', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7aYTCCjQ#AA6utgCaWzARAtqCGYXIDgB4TiUAHbA_ER1dCRnfgqQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Los otros hermanos Elric - Segunda parte', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mPYiRDRL#ADJUoAA996Q5AXXeNzjAIQDcqTQAtQPoOVcwLzeoRYQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=1),
        'Fuego vs. Acero', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/LC4WEYbJ#ANDDVwB5eCQJUvsHx1nRJgBoTGYAGf_kCRdvi8djGaA'),


--'Fullmetal Alchemist' - 12 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'El brazo derecho de la destrucción', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/Wewy2BaA#APvj9wBJTkAGVT3drN0UiQA3WdoAb5e9Bk-8i6ym4-E'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La masacre de Ishval', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bb4jXbjS#AEPdqQB-LrIohcO2cHglnQAZSaQAgispKEZs93C9Wy0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Pérdidas', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WapRwALS#AA2-SwC_A8PGD184gG69TQB1WhIAtqOkxlSy-YDYU9s'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La casa donde espera la familia', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/jaYz3YQQ#AGKvZQBYfNEt89c0lX_23ADoyQ4AExxsLepr2pXQpHo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La nota de Marcoh', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/TSJkSYaT#AMkjwAAD0xM3vh1P6KpfSgAjvj8AhxbjNzKlLehVI8s'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'La verdad detrás de la verdad', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/naBz0IiL#AOAtwACSSlgU4VKqtbRCwgARM8kA3IrWFHqM67WwIsg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'El alma del guardián', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6ChxBAJb#AOg8WQCxdW4bkZk11wwubQCJV2sA98M7G7LX4tcs57A'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Brillo Carmesí', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/XCpTQBzR#AJzD6wBsYuWEtciS_lJcIQBAfaAAZAmEhL9Xqf6MI3U'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Humano creado', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/GPZiFbjA#APx1uADuoPrrtHRysXxkRABz9w8AlZoR6xTlEbHrgQQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Corazón de acero', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/LKo2BBQZ#AAd3aQAPQ8jJYH2bIrYqsgC0CVwASPe2yVP7SSK6T7s'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Recuerdos implantados', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/LaYAnDYB#AGIVfgDa0xtkXGQLZ_5cbQCyz6kAMhYGZP-Q_mcXSsc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=2),
        'Ceremonia de despedida', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/2DwHyJja#AMZZRQBJInpNPUGac15p-gD5V0sAZN22TWjoinOeplE'),


--'Fullmetal Alchemist' - 16 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Su razón', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/CDBwFC4Q#AOeIsQCxX8ehLTZbdLaPTgBnNvwA8AQ0oXjXiXR6faw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Maestro', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mDgH2DBZ#ALxevwCBuoJvXuaxRdjMVABhYggAZKxTb0rSRkUz6_0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Uno es todo, todo es uno', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DCAwnSyB#AA_68wD7ukJ8GQXLzKCOEwCGkvMAPzM-fMOlEcy9OX8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Niño inocente', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/nHIjGAqB#ABWABwCGx8h8gFX3erLKuwC3PbIA3LvrfOazoHpGySI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Asalto al Cuartel General del Sur', 5, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/PWBWGZoC#AHlnbAAGGZaEIQuBcKUiPAAuw_cAQXochAUkRXBvNY8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Pecado', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/zHYm2bCA#AKudyACnMyTx0HdWZeypOQB55asAu_2_8fm5Z2VKo4M'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El profundo bosque de Dante', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/BdkQQY5J#n4UwqVzBDq6PrAYu-n0Mcbtuq8BRLokQoZMaPid8Ie4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Al secuestrado', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/LTBk0DxS#ALYseQD_rZOzKlm57Z4pYwAbTMAAtJmDs6lH6e2prOo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Teoría de la avaricia', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qfZzzAzY#ABKG4AC68qqk_TdjS2X4XwBVdaQAgjjIpFWqtUutVCM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Reunión de los Caídos', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/nHQWhKhI#AElynwBlFHqjx-XSVj8xnwCB89kAsA7Qo3ktylbqLAA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El Pecador interno', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mSgVWTBb#AL6O4QBNYzzqsAP3pjQLuAApx7IAY4i56vFvtKbf68g'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'El Alquimista de Fuego, el Teniente Soltero y el Misterio del Almacén 13', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/uSQi2LRQ#AE0OTgAQ4MXVq0f5gsGMsAC54FEAY6tf1YYcrYIzTYs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Con el fluir del río', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/yaRmwD7D#ANnkKwCbHrNn_86-KObOsQAby_gAOI0oZ1gc6SgYHVo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Guerra Civil del Este', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WHYhDRIB#AOMoHAAgHtPafmoPM4bINwACUKUAexi22oy4dTMIe7E'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'La Cicatriz', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mHhl2YCT#ACskGwBA5lxv6GP5iN7zAAAVNOEArRWjb1hlWoi0lpo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=3),
        'Madre Santa', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7e5AkAxC#AJdOeQCLlq_hOn3KPe7GVQCxgkQAEjpr4f3U4z2Blq4'),

--'Fullmetal Alchemist' - 10 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Su nombre es desconocido', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/eb5Q1TiC#AF2R0gD1Hmo61fXK9SLDOwDR6I0A-zBNOp3Dj_XU1CA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'El perro callejero', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/raJHSBaB#AGQJCAAcld30o1KCHohuHwAWKjIAczKG9Kk5sB6beuw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Hohenheim de la Luz', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WWRwlI5C#AG2R0wAlfueD1GRkKugylgBDNO0ATxgVg2VSGSqKJ-g'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Alma corrupta', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qSI3BTDL#AGNPzQBH7mIOj9iqXW9LyQCYo4sAvALgDqR1v12FuiI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Transmutación Humana', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/XCA1hJoC#AKYHzgBqk4ToARgiwMiLQAD6lh8AlFqX6OZp_sBK09A'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Sellando a los homúnculos', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3TomhQxJ#ADq6zQCRr5GKCjW9Up1VjwAsyzcAumLSimaQyVKcc9Q'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Adiós', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/HfZXRRiL#ABI3UgDwnCOko-nMLgrbEQBgJCcATAJZpD5tKS5IkMI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'El otro lado de la Puerta', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mWQEhYzI#AMTheQBDTZtxmCOH9-J5gwBV8UgA-QMocUs4vPersqA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Muerte', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/XXJSBYRT#ACG8SAC98SMoUwYrlbiZ0wD40zwAGc2TKNm4kJWs094'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist') AND num=4),
        'Munich 1921', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/HD51gYga#AEWOtgAjK_F4r4v9FPikZQASrgEAE6BWeBuovhR87k0')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis, link) VALUES
--'Fullmetal Alchemist Brotherhood' - 14 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El Alquimista de Acero', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qfoFSCJJ#AKfYPgCnePpLmJCTJ_6cVwDPAewAjIDbS99N3Ccvyqo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El día del inicio', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/GGJSTTSZ#AH8k4gD46XW4GFiMD8moTQBADO4AImbzuBiwVg8on8M'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La ciudad de la herejía', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DXYxULzB#ALGMNgCcE6QxhSzP0XPebgA39WIABNixMfZJn9EBswg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La angustia de un Alquimista', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/jK42nDwD#AONQnAAgC4TH9f0GRa2qYwCh7LYA41vwx4pAMkVQw8M'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Lluvia de trizteza', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ee4jgJQL#AHj_jQDARWMecMDdyfFjdgBjSY4AvJWBHoBdcMkvgNo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'El camino hacia la esperanza', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/KP5XSKRQ#AMaEDQD4XK4LB8sjNXtcywAVqJwAv-sfC_x8QjX_1oE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'La verdad oculta', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qSR2yYaR#AP1R2wAZ3BR0jBcgJ8i61QALb5EAxk7QdKruryckQIs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Investigando el Laboratorio número 5', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/zeJjHbRL#AO01PQBfWhps97XZRIi9LwDgLCAAM3__bCPNvkTOnz8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Sentimientos creados', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6e4wQCBJ#APY6hQCT4x-XG4QhVqb_WwDo6XIA5c5nl56PolaQjlo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Cada destino', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/jC5lzJTS#AMJeyQAIkscmOl2ydcC29gBa7-8AbaMiJl5xnXWfnps'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Milagro en Rush Valley', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/TCAiVApK#AIm7mQC_j2AFQbHXUu7abQAvQp8AOIsdBaYKflLBp_o'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Uno es todo, y todo es uno', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/uC5jkb4Z#AFy9MQB6jUxxQCcyWWAN9AC3lgIAB4lecTXJOFl6MnU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Las bestias de Dublith', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DWRljagK#AE4IvgBllT6P7lKDKIhFBgDUN2QACvJ5j8d5hCgtG3Y'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=1),
        'Aquellos que acechan bajo la tierra', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6aYHhBQR#AHwfXwAs7gyXaKVxb2KFDQAZM9sArJ8fl3uC9W_7X_g'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Emisario del Este', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ybARgDoa#ADsKFQDfRldzgYE3hZJcJADzwIAA2a8Tc2mWWoVuggY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Pasos de un camarada de guerra', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DHRRjTJJ#AJ2vHAAVCPOul3sJ1dQdhAAgXTYACWfwrqKox9WR8FE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Llamas serenas', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7fY0GKJa#AAjN3QAtLGCUHBgw47L0UwDqdRIAJXGylLrKp-MmGAg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'En la palma de un humano arrogante', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/nKZDCKjI#AA2WkQBcGpboeEuJPqXnHwByXxAAr6F_6PSjwj4p40Y'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La muerte del inmortal', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/rfwwVSKS#AJOUKwBAEwQ01Umy7SoE-wAvAL8Ax52xNGVueO0-UZ0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Padre frente a la tumba', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IdhUhBjQ#URQ1z-5tKooQJkHNPoH-Qt47Zb8GemY5swpDq7fnZUw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'El progreso del tonto', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qPRDkC7R#AP_krgDFjIMzgIuAdEiJvACN6TEAua6BMzG3aHSRzE0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Espaldas distantes', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/KC4mQQJQ#AERzhQB8xkyRKPtAgp_vlwC1zlwAKu1SkRdZlYIbHa4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La chica de la guerra', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3XIzmLrC#AKSg-gAzsK4X9IhmRvIUhQBKgcMA_yoZFy_0T0b3R6Y'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Dentro del estómago', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/yfwmFSYA#AK5VnwBKnruy1KBPVAICWADnqEoAHEfUsr8mVlRw6hU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'La puerta de la oscuridad', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/AcwXUKIC#wH1wYSIASaM1yjTFDSyvWY670ISFxuJsrQlymPvT6wM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=2),
        'Reunión', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/rTBzSApJ#AKAzuQBr9-1baSjtAXTaTADmGtwAw0gxW2pcUAE7mCM'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Banquete en la grieta', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/PDZ1GAJS#ABW1TABZBSoILxBA4_rNvACFrCoAPiC6CMSAduPnWZo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Padre', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6bRR1aAR#ADp7kgAeS5XhEOpQcLBEnQDlH3QAVq064f1eYXBFrQg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La lucha del tonto', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/XGpxjI6Z#AE636gC3rSEyBfrgCjjSUwA7hUMAHK1eMhCgVgrjivw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La campaña de aniquilación de Ishbal', 4, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/LP4gQDhQ#AMBp2wCq9mVfQkw9Z5AkvgB4VaUAEYfIX1bz02dtwY4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La promesa hecha por 520 Cenz', 5, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/OagXkQra#AF-pcQD48u8PVDu3m9PY0wBGxlwAy0DeDyDk_JsK-CE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'El hijo del Führer', 6, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/LSZk1AJS#APe_EACHqfYq7LcSypN5dQCK8KIA_eWMKlRtysp7DzM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La muralla del norte de Briggs', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/KPREkJLT#AKkdgACTrwRbODkt-O8KZwDBp84At8kdWwmsmfjThMg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La Reina de Hielo', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/MwcWiSSL#Vgxk52esG5ZBfOjWRcRNKIOZLSqe28VRVusw65UQ1rk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'La forma de este país', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/GLJgGT6a#ALJoNgDuG5pe0m0JV70wqgBrjF4AkArhXlAi1Vc2X2k'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Retrato de familia', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/p0cW3apA#TGtHumeCQ4epPglIw2qwqWLdSwV3zsQFxEfXIpj1b8Q'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'El homúnculo original', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mTw3yaLK#AAVJuQAYQgpYm7DWscvrLwB58FIALNqoWNneurEXPX0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=3),
        'Conflicto en Baschool', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/eHRjlJYC#AF1xRQCMhmIo4oBYdPKlaQAqSNwA4RpqKDIYTXQmwD4'),


--'Fullmetal Alchemist Brotherhood' - 12 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Soñar despierto', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/zXxmQJqD#AAmNCQBL45UF-W0oYhEWOQCGv_UACEE1BaU-kmJpAo0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La criatura dentro del frasco', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/NIpT2QZT#GGhM4b6zSzjfHmnmA8zG0hqsXrB-yg71upqFuBTpSrQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Infierno', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/1E4D3QKA#AQmN75rq9PvzuK8QyDB_PCxiLTa6673RO70SmgmnpzY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Señales de un contraataque', 4, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/0con0AjR#7Qyu3luFXvtQyDHOwADG3sIJyXS_gT1YC4gUstcrTdA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La mordedura de una hormiga', 5, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/9MwhVAZJ#B7CJfwwtf-s75La1tC8rZqUydlwX6exY7zFK7kVZemo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Una recuperación completa', 6, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/wIxTia7Q#8TjZW7vkLewHoknAGD-6-jQZjIZYAUZRvpJFu4uhXpw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'El día prometido', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/RA4XzK4Y#gENN8eIQdThvv3lJ4wtpHegN0Gjr_Kf9Ea6t-a5fTDo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'La sombra cautelosa', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/dJg3XS4b#RVWO4ty3FQfQ2iIeEVE3z-Mst22dHEkUWMYpCIovVd0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Mensajero de la oscuridad', 9, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/bEKtOVRe5O8G'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Un juramento hecho bajo tierra', 10, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/gNoXgCJK#Iy-ft4l1zA2PAdeuvtYATnAKeZcTAIjDyXaRkqNIm64'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'El amor de un padre y un hijo', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/sdoTUIab#xDulmOx1MOEJOEXsOHXcpNUskvvJpz0UJNYpj7dmsNc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=4),
        'Agitación en Central', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kN5FWSxD#IuKramfPOom7OTBeXK8NLHZmUjtLDxfmLvICwKOK_Ts'),


--'Fullmetal Alchemist Brotherhood' - 14 episodios 5 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Ejército inmortal', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/QJoXAazI#UQbhHcOWRVzPZ5qKLXAO-MzE1UxxiaYSLaOP_HaShE4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El poder de todos', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/Md5VGCgJ#4Y6fkpCESw3gfVLTDP2e9cTpteqTQI0yZhIluJGfwM8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Las llamas de la venganza', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/lFgBiKAT#XOv9UlFqbvb7MzKZXmu-HStkM6f6X92NziZP7EWjhac'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Detrás de las llamas', 4, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/UEh3DYYD#OxDDBssurArRgOrvaIhU_s5q6KYrsoKDhhuswVIObVY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'La manera de vivir de los adultos', 5, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/4JxTXK6D#ESrCPGxQGpL3VYArbHJReCuNV32qpgBJXONGhgPWtFE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El regreso del Führer', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/AM4hRC4Y#PbhBbIWJNmMbm9SQvX49sqRJHg7Y-P0npetz4gx-zAs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Descanso Eterno', 7, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/1RpTxIQB#PcXcf0A4ly64ttCn7iGKy0iXGsFowRpJDwxq77FAWzY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Sacrificios humanos', 8, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/JEhDRIoK#aYb-nWoCriNBSupM_8u58M9SD-H8KLDbuIFTJkJyRek'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Luz perdida', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/lApXXILK#GGL1-PMtle3DZY--9NCHlB7DBKD6UsmVq5C0g1gI7PQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El ojo del cielo, la puerta de la Tierra', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/gYpX0a6B#_Bq3ff1DzMo0FADJx01lpPm2Z3WB-vN9wJyCQiLCkLk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Aquel que se tragó a Dios', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/9c4XDCZJ#kQkdtUdINsm8ph9B5I8dQa0WVBDRf4EiJumw-NJXN2E'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'Contraataque violento', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/JBgFlKQR#10xhqjDTtc3EyTTbtQMiDe7ZqBXzu0vDHtm9NussIQc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El otro lado de la puerta', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oBh30aJL#etxVtLQRDCrWaDZBSnHVYMOb_KncAytNABWP59Ch2Xg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Fullmetal Alchemist Brotherhood') AND num=5),
        'El final del viaje', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oBpxwQTT#r9rZH6QpaWHCCI_65Qc8VzGfXECVFlTKYcXIOGrFHVU')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis, link) VALUES
--'Haikyuu' - 25 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El Fin y el Comienzo', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/NYphlIAT#TvNx_aGJ6ZsTn1RQdyLJrlYpHRYY8dgHi93sT9JINLY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Club de Voleibol de la Preparatoria Karasuno', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/1RoRhQwQ#3rScgnYB-ljbnAKEFDbNy0EgF17IiBd3tAlqhX3rh3Y'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El aliado más fuerte', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/YB5R2AQI#0BkRRbNr3zyAXPZZpLqfB-jpe1_U3wEEkN6jV4gMb1A'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'La vista desde la cima', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IYgBjY6R#Wa7YlP7tqk3KYcH9gn2jFVnVpHoIlzzOpmQE1e-sMRY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El nerviosismo de un cobarde', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/YconXapD#TYo0E3LEveEctjFvbOd1HHOvrAAH0jrTPAXcq7COBPE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Un equipo interesante', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bQwiTRRa#0JsvqgSppzDX0I4B2a0KHG7oaMv1tGVtkAdMGdigAFY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Contra el Gran Rey', 7, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/BdglkAIZ#BdBQmYWobdqzB-Q1mRdMJH8zTh6t17r8qYWfWzICB1I'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Aquel al que llaman estrella', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/KcxSgDKT#6cIhNvWnWFOmnUiZ1v--C8wOvlcbcvl45Tmj1zV-nP0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Un pase para la estrella', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3MgWmDQJ#uv4OePCBKM54OKDzwHdcD6V3sERcsGa3EXLnhjP7WRU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Anhelo', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/PUpiCDba#mC0a0LxWvDRiqaDjTAGnf0p1_Z_T3Qro9Y663G2mlGY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Decisión', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bch2mJKA#rp4uQTnOXm-wpzW0SR38-7nZI7peZiRSM9OahVGuue0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'La reunión de gatos y cuervos', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bAxGyJaZ#zmG-AroH2hzIKcYfQ1Qjwc9qF2e7t16CasYrZTxf-fQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Rivales', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/mNhEERBK#pDmhQBW5FHET9_OaXI6gq5nsLKqvvt1X0hHjW83dnow'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Oponentes formidables', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/aNhWlLKK#KlAZN1aUFG63S5Fu_YbNpiA2X7vKRYyQpuR6aTZQZhc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Renacimiento', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/fJxGFToY#ls0Hqcq7I9mgabU2XiZy06fAWoxjHTuY3jG9ND57Otw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Ganadores y Perdedores', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/aFp2RBpS#N8mMloZ_h5j9Woo0DH3qo_y8WwUt8Tln8ezVxEFQ0Pk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El Muro de Acero', 17, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6Yp0yJxb#isLYAsq1f_SxjmKJdE08McoSea-wlHyjb-eaKxw80rU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Cubriendo sus espaldas', 18, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/OMoSzRKQ#bTGQiysv2-hRM2q5A6zaY_QgqBpcA5jUG0fzM-BSZ9U'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Directores', 19, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/XAgylBRK#6YPu-0vSUbIgdR644CSh_V6D8eke6Sc7XomQqXuTzYM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Toru Oikawa no es un genio', 20, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/HBh2FBLC#01PaemKXnXee1e-AgmQb1n_IvlGNBAc5qpfsOA2gtOk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Las verdaderas habilidades del senpai', 21, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/eQpQzT5b#YRZyue_TxBGn9qLu75oHCz0QG9lyNS_IZNmeU9gi3Nk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Evolución', 22, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/iYowURqK#3XeDeoty9t7UMRb7n18agNkW-fD2mTSm2vmgGTZbUfU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El punto que cambia la corriente', 23, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/vVwEQTxR#itMnEBhG6kFRHJriXSDQ9W_zbX8LlmkYzL_QQuFF2gA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'Retirando al rey solitario', 24, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/LRo0nLab#c7LyRdWboU0RXPLmrLNutKtiVF1OYC89B7rBoujjoZQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=1),
        'El tercer día', 25, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/iN5wTJrB#ML7dAe0fFYTNXDjmsm8vZ3DmnJXrMdXFBwukKgkD4So'),


--'Haikyuu' - 25 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        '¡Vamos a Tokyo!', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/0BonQC6S#tgNKFh_O5zeT6cLIAjfiVK9k4NGPczhOXcwRwlocH08'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Luz Solar Directa', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/eHQUVDqC#38lg0H40158bQp9Koh_Ysc3ic8EmxWoLFbbDzFhQRu0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Poblador B', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/YBhHAKyJ#xLb571cEoCSi8YMAjWmLZAeUhJQbpUAqLAK45p38iOw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Estrella Central', 4, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/80HCTu3lRbax'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Codicia', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/5AYXgQxD#8O1B1-ZyFDEYrNQ2G_xi5-c3kXp-uhf9fDD32_WKo-c'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Ritmo', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/VUBBjSID#tlw2U2r7I7-1Yr7M3cjWOlL6soJaWZKJeXZBRK4ojNU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Salida de la luna', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/9IInhC4S#2p9QtvTwr2x57KYurT9y5pTGSSQapJG1vGPYEI8mtWk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Héroe ilusorio', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/5BBTmCKL#dq0M0gXa5dEGdvdvc-TiPz1ORv7D_S526C77-Iq9qiY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'vs Un paraguas', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/wQQHCIIZ#LcL-ZUWkxTdo1t_3tGAmMQS1NdIWMzQtCks25xfaSec'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Engranajes', 10, 'Lorem ipsum dolor sit amet',
         'https://www.yourupload.com/watch/3e2n8fY1LcpS'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Arriba', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/lYZznIiS#dkCa5FTUFv0uRXOu0LIBlFGDi7CGH0jUkgwP13yhzoU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        '¡Empiezan los partidos!', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/RNRFwYCS#bpchA6K0OQg615xKGxwqyd8PARlbqcjYl17md09ig8w'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Un poder simple y puro', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/BVJlRCiJ#-SpeP_yRO-7teBqC9JP7eCg_bSlS9U7Fd1edFcdoOuA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Aún en crecimiento', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kBJ3UATJ#TUhtOqmz3vhfgIoEvlqa8AQIUssselGxvLQoPLuv_Uo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Un lugar para jugar', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/REBl3QCQ#utuG5GwXPtPUyUDoDwXtMZsYH0YzyvOnjhVG2bqnqiQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Siguiente', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/dYZjRY6b#V4Qf5H2D9G3SzUiOBDssUJpkVbOtgsJp2quZGiZmOY0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'La batalla sin fuerza de voluntad', 17, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/gdYF2CJY#Dx6w7QLk2xeF-owCEoBcGs5RP3WrwXZvKoDauRN5J_0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Los perdedores', 18, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/UQJRCALQ#MX5TTpYiuDPrpDQJbOOw-6HPCQAPQnWVd3pLo1C1Gcg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El Muro de Acero puede reconstruirse una y otra vez', 19, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IIAF0YgB#RgOdYOoZkIY5BiJRwj9-d-de4aMN2oGk1nqw1o0Rk1w'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Eliminando', 20, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/VBJHBAwL#kgvNi3r4whZ0A22zRvpib4PQnM2MIqYQxonbcUMeH6I'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El Destructor', 21, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ZYRhmayA#kXeWMAewUrmH64uJCFMzMwYaaqfVURdvUSRD18u5aL4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'La pelea del antiguo cobarde', 22, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/UJZB2aLC#NVZlCgfdLLg7R1obJBxrvOSutUg3coQCnBH2pQkRfBE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Equipo', 23, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/lUJnRQ7b#WMbF-s328mF2IqtNke7HpgTqbdNxU3v6UBPgoHGbJtg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'El interruptor del límite absoluto', 24, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/0EY3VIBa#mrpdyfGWCY3azzq8AzgFB_frkrWn8zCOQrMVlL2MGHM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=2),
        'Declaración de guerra', 25, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/sMZ3EYTQ#EanYOepgB9s7zHoznF0VvAXgXNPm6GoVKPdYLJKmJlI'),


--'Haikyuu' - 10 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Saludos', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/1kFmiBBR#VwJMi0P5LvIAkEq5sFCnoapRiO-tsmEhxrMbF5q61R4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La amenaza del zurdo', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/olcy1RCS#i2pKMLpdwjpAzLsgqJy5W-Ab9Ae63U-J_aMnhfh_miI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'GUESS-MONSTER', 3, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/GfJUxJYZ#JqYqhxbsdwm7EwPYxlkyqMCgj95hN1QlDqGR5N9S3ig'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La aureola que rodea la luna', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/8gEkQZ6J#0zV-58UKEhviUfMsJMoReL4HG3H9DsVXw3nZFVOqYu4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Individual vs Números', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/QkEyxZ4b#K2-Sg-YI4NgF2v4aXPxnp93YKPLuVOogjWcgwJN5f1w'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La reacción química de los encuentros', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/JtdSmZhI#yFmznbgh-MA27MC5sFXMpFKtZ2-RnnaVdgAjZniTZko'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Obsesión', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/50EmhTaI#REWWcVnZ-3ssa7_pDa7UuKBi6yuHLgfSEWbXn_bDbKg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Un tipo molesto', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/w8UmHLJT#FniPS8SjceHIjy2ygjgMjSlMUDJbffKUWGLK32Dp94M'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'Idiotas del voleibol', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/shMAlJRa#IZDiDoIL9DlLsz0FnSIQs1F5iD0P_qhXkEhg-xC9MDY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=3),
        'La batalla de conceptos', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/00dw0ZrD#MqB-z074vBOtl5a3Y9LWHr0qUejEbFieZpfL55JPHeU'),


--'Haikyuu' - 25 episodios 4 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Presentaciones', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WKRWyTZY#XZhHieeAnijdCw5r-mzxOV35fgav-r6lwGgup8Ak48o'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Perdido', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qOIkDZDL#-VA-Yn3RXOROWTxV8ECjXBDG5BpLap5UswdFIgVidOA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Punto de vista', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/jGIG2BiJ#nT6fx4s5tEEgBY6cpCq7sG4hw5T1-MYAF9qNqQyjviU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Tomarlo con calma', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/TGZiGZpA#4djNYsStKQ_63O8JTTeuw-BQKOfR8JRgPhbTe8GnQkc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Hambre', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/nXQS3ZJY#zfncCAmgaIulSxfm8prgKuba-7gHDE6-n4MRr_Pue98'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Mejoras', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/iWAWhJRI#SzuKRjnqPGz9a0K9xBKrPxbOjS8pw5dd-WNE8xpTxm8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Regreso', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/2aAiQbaI#NAnxFyJV1DfDr2aLIrTV6DmZKxHc51cIpNZR-S0gsTs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Retador', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bfYW3RJY#EAUtzpvahQTlRF8g0mHorlEDXAyXZR6Y99MPwhk_USk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Una noche para todos', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/neZ0RbKJ#DpQHiip4vHSGKhJKZEsVXY_Qiu6pItVr2TVMoYE1VnY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Frente de batalla', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/SXJSnb7J#xVOHDvgj3HOcQV4XQGYYnxJ_AFxO_-h9Llh4tAx2cVM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Una oportunidad de conectar', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ifQiHZBS#CQVrBd-KQYpa-Xoafag-SyHgHQorFPdkRNNw23UZBf4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Vívido', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/rLIwXZRY#LdjJTKTIT406JA9b5FuexVPwjr5_P6C3iUfxJTVsV8I'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El segundo día', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/rDR00L7I#uhHI4eDA2Y9Xa1viO9chjNcrUw7P8BLW2qNc5Gn9E54'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Ritmo', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WXQ2mTaT#nnCz9jDUjccoAQjicRJjFeLfI3mXlLsB_K-2xVfQes0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Encontrar', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/CGREUDya#yveuKe4S32vvm56Z1_lWwdkqaoOjMsQdE76ztZRbSsQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Corazón Roto', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/uHYWXTYD#t5QwU9Ptkm5xIUqL1RVnsbNeacHFL19n0RGd6XbJkIw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Gatos vs Monos', 17, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3bQwBDyK#_EdDQBPY6EX5J9Gd4zd3ytZsD4ItIdqcsGUTqVCsTuA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Trampa', 18, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/qeY2HZJT#JbUq9-zMkBtVnVTTOBIjxepQDbQBjgatbPu0_nZCcyA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El retador más fuerte', 19, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/6SBQRZxK#k1tJxSZ0k4wljfuIi9xpmuHlpmyKtoz0Qc5dJXGFlGQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Líder', 20, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/CWQySDRa#cyK32UVBLrrEhID69Odt6dxdR-0WzqF00LMbHTeSmxU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Héroe', 21, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/yw15myd8ywa4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Clavija', 22, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/o5HubT60d7DE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El nacimiento del rey silencioso', 23, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/0cC47q3pMO7W'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'El festín de los monstruos', 24, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/ptH24KpTLUR0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Haikyuu!') AND num=4),
        'Tierra prometida', 25, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/OU8fx0y4WS84')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis, link) VALUES
--'Hanako-kun' - 12 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 1: Hanako-san de los Baños', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/DKo1gYaZ#NXXM2o-CL5Z6Zi2pXyN7K7poEMJPW4p1MWezGQtZ7BE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 2: Yousei-san', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/uqYghBBZ#lTbrrOl-mVcmQZFck7HdS8U6mddMISfdEG3CLliaMSA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 3: Las Escaleras Misaki, Parte 1', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/aiBDmArD#nq7bnWKkH_MamyHELs9MRzD7AG6orWsdfEbjYxOY6ts'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 3: Las Escaleras Misaki, Parte 2', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/OQERCIhD#Sv2woQuyQ_dh4vhjVorScY81qorzZ2kObTpn4hMQFSk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 5: El Árbol de la Confesión', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/2dVXTaiJ#29EmND7e72GxLYFdsN4AxntsRuEwTFD9A8V87oZVp7s'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 6: La Biblioteca de las 4 en Punto', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bPxhnSKY#72L8xk-mAmO2csF6iJX2JEoafd9mxn9n3n9CGms80LI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 7: Donas', 7, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/V5gwSCKb#FM6aFu86Sua8JHGXSsYIMPCpDlRmD7KNoJtT1deT8Dc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 8: Mitsuba', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/KCxT3CIb#N9d5GhxTraD8Mn7koyckM9sBI07aT_kZ8u9ByHz8exk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 9: La Fiesta del te', 9, 'Lorem ipsum dolor sit amet',
         'https://mega.nz/file/qoZFBQSB#bQbs3pKMzfbU1nAFB6W4s8YsI99472Vo1zF-MulaKyU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 10: El Infierno de los Espejos, Parte 1', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/2QdjmYrZ#iC3HmbEbB1Ya_Vv6z8DLq6Zd2l7NkH1GwfFKQE_VKfI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 10: El Infierno de los Espejos, Parte 2', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/OSARXQaJ#L4W89D0ylJqAEjOYXAQowq33FeWCSVyh8LLu8BA2AMs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Jibaku Shonen Hanako-kun') AND num=1),
        'Aparición 12: La sirenita', 12, 'Lorem ipsum dolor sit amet 2',
        'https://mega.nz/file/SdN3AKTA#rBNOcskVnhrm0ZBcHbt3oQcBQhhAho8ktnu-8whKASs')
;

--  ----------------------------------------------------------------------------------------

INSERT INTO episode(seasonid, name, num, synopsis, link) VALUES
--'Cardcaptor Sakura' - 35 episodios 1 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el misterioso libro mágico', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oJYWEDjY#2KYyBuO4E7kRO3QKy73TmKew6bSzpiBiCSWO6KaxPNo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La preciosa amiga de Sakura', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/EQZiEbYL#7HE14l0bR10evdiwu0e93zuVjiSafooICaD4NZX2Rog'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La primera cita de Sakura', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/dFZUBZJC#lHrm6rvnMyVI_7ofiOR64l4wPXuUy4PmeZ3eRQZPt54'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Agotador Domingo de Sakura', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/gBN2xTDK#p8NhDr5v-qyXko05OmsCBtj40VPqp1s21qzyCUxNQ4A'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, el Panda y la Tienda Maravillosa', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/EJZC2Dqa#j6_cpMwvKD3u7pJQUeWHULrMIw4YXeC1W1sv01e0Kto'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y los Recuerdos de su Madre', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IUQwUD5L#TeHwWyScn1a6MIi3XGxltiHFX8ukZ66BMIB0OyGsD_U'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Primera Batalla de Sakura contra un Misterioso Ladrón', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/sFRwFLhb#UfFsidapSdUVpWvjPoGjY2BGKHdi2O-l2fdKZ0qcxC8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Rival de Sakura', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/0QQWHBCS#2zhyzJnU7kiu23kEBScX6_uaGy52a7AyNOvfQ7EagkI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Broche Misterioso', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/hNAglZqB#fYLy5-sbaH0UMVOobCVNgGguF4mn-t_350Hd2KkmBtw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Campeonato y las Flores', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/BQBiVDKL#KT_0DxJITWbgWRR4CZ7D0QNn1CbV4F3kg-6ZnGPe7Uk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Tomoyo y la Gran Mansión', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kNZglbgK#M8okBbSgdTnkdShnQEes4YPFjVOL4hvnRgY3ccPuVJ0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'El Día Interminable de Sakura', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/dQRymRyJ#2TpiTL4nWGE2lwVvnM785-VsyTpw2zWW_AgPlAn4Neg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Elefante en la Competición de Fuerza', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/cMB0UByD#KqLIPIdpm4s-Vdzf4DJhKvBvQ7_BCJhO4gPbeQG53uo'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Touya y la Cenicienta', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/8IZQxbJY#WthzL-wh017JuZ_SqAYlD0yz8pt9B_1NG3Z6voTnIPQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Gran Pelea de Sakura y Kero', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/9cIgkL7I#ycMgFrp1k3fWewpCHfTHqgoYBbnGy_96drmUUevugJM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Arcoiris del Recuerdo', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ZZR0nRhS#_shXr41jJEBoMgr-E_lrqOXN7RQjdeH1hvEnnJyB8-E'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Terrorífica Prueba de Valor de Sakura', 17, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/EVYwwLIQ#qB8P23wlPIyh9RzMLVbojNNu7W9eJ_0PNyqjSJWXfkQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Yukito y la Feria de Verano', 18, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/YIAhDYxY#QiTriAhdkzCWQRfsfwuCzcdP7GxKisn08Cr0c0w_6V0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y los deberes del Verano', 19, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/AUZzjIIR#RFsMOp6Ej_J6j5-Dyi4ClpeDInfEfCgofAKg47mSiPc'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Nueva Enemiga de Sakura', 20, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/bLwU4eiacJCw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Larga Carrera de Maratón de Sakura', 21, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/1QIxnayI#xKDv1yKiPn7uVqb6KDvkZnZKkTWUq0qcKMUXHRDK9R4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y su Amable Padre', 22, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/3qO22oVTNO7I'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Tomoyo y una Hermosa Canción', 23, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kFRTDKpL#eVEvWd9fXsx4Kp5wO8b5VNFBHwwEVafZN5dg4zK5Uz8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'La Pequeña Gran Aventura de Sakura', 24, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/UFYhmYaJ#uICi0XxjyzWbSJLXLys1B-DZ_tz_55nJD_ADVPCLsuw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la otra Sakura', 25, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oAIG2TIC#CR2jAVSdXrPhQontdNp6XK_9EyQfx039o9Oi8ZLBSZQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y su Bellísima Profesora', 26, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IBJhzQoS#5MJstqL-gbfsx2ERZYiDXUZbzB6wf5OEWoRu5Z0XgTM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Templo de Los Recuerdos', 27, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/VAR3EC4A#IDrtzLWkGis-dx-2JiN2dS7vInaj3Y1rBRMKf3z4mn8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y sus Cartas Mágicas', 28, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oFZTzY7a#BUz8DpgLME9pI-D8lWs8bUv1QAPAyv4OWyWrqWSdHWw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Repostería', 29, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/cMQXTSTT#ukBtN7kP7WqUOqLjtPg68w12ecgXhfu5h_d6AI6ZQsg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Carta Herida', 30, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/MVIXGIwZ#athqoOyzzlUdm_Uw2tmrSlTwNLGXdNZRcoE7kQ-EsKg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y el Libro sin Nombre', 31, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/MQRFDKIZ#2ssZCBJ4Pucbkwbxiiy8RdHkVRrMCsqcKvvUmsFo9zA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Syaoran y Kero', 32, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/lIAX2K6Z#B_2z_8syWXDfhXx3QdJ7nHP2d3XYTE4I0zseO9aPMJI'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura y la Carta de Hielo', 33, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/RJBj1YxD#UQJoAIOWPdpXCEzvM_RvslyJOfbh0bIfxZqN-taOHnA'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Sakura, Yukito y la Luna Llena', 34, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kcA0FRpB#HXO0UegA4lM8gzwbn0XJjQj8gtyAnzbnuW0u1ioTluE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=1),
        'Que maravilla de Navidad', 35, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/JVQhVYQI#A_fAeRMrV-1rGmPbngV1yjT_2IUn_vB697-N-ZYnJ5M'),


--'Cardcaptor Sakura' - 11 episodios 2 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Yukito y el Nuevo Curso Escolar', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/IEYmRbpR#5RxqcIkZ5KKJeq6MXyQJoFFpuH5izkFvWJzbxHHuXbw'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y La Pérdida de Voz De Tomoyo', 2, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/QAIXAIqQ#RAw2qg162RQnnq1bRYpNXLmC8JD2jWCY1Yu0G5DIYXM'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y La Aventura De Coger Fresas', 3, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/G0qU7ScbO8CW'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Día de Fiebre y Mareos', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/MdJDHSiS#Vw3BsmHypXIjvMYlgbqPOHJSgqvFnzIIGFvDcFeFuQ4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Sueño', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/EBIDjQqK#k4_rnU7vXOuHEzN6DJZsqfDK1L3vmRX9K8FM2eUceCs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Syaoran y el Mar de Arena', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/tAZ1AAyI#R0aE2LNZUhjHaeKe8-ExvttY9Jd-PyJBO_BSspLGNzU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Festival de las Artes', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/1QQFESqL#qopIU2H1HlJneXE9qYKz3OnIygp5y-Z8JOOL2PttOzg'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y la Despedida de Meilin', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/FEBVEK7D#r4BgjJyA7VKplu1RpAjbvwxoZIsQhGpPLkdmgI2Q0bU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura, Kero y la Misteriosa Profesora', 9, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/VEB3AIRA#vN3PXRz0FPq4sxt4FN5M64_HFgq6v5VspF4l5YNx98o'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y la Última Carta de Clow', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/5cYhQKoQ#iS2TK2JIoiL0tsF_fSLkrDKvvtYL2dCROVeC_-g2EQ8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=2),
        'Sakura y el Juicio Final', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/NdQDwSJJ#0bIXHTBayHpZPoSM7SCO6ntvJeopQb__oRlQUXaxiUM'),


--'Cardcaptor Sakura' - 24 episodios 3 temporada
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Misterioso Estudiante Nuevo', 1, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/9AIzGIIS#EkYA-im9uZoMSInmxYvSWkAV3psSYQcgPm-lb5sFF88'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Despertar de la Llave Estrella', 2, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/N8l447jddcyr'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Piano Peligroso', 3, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/oQZTEYIR#DSnS6VxjZLYjb0z2E6qtDf8KtdbESikHNyioqmzRLGE'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Hilo Invisible', 4, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/8IJ1CQQR#aPb3YXZq5Tr-ej37FTOkjjOj1k7r1OkzLet-CwGPT-k'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el abrazo del peluche', 5, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/4cYTwAYB#wANLay_NXF5JrHepwD6cCs-53rVAmMFI1q77zp6DK54'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Aviso de las Ovejas', 6, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/FcYR1KoS#s_fr1CGiQS2Lc4UwgxKUX2qx5ltaR7qgmDeKTepuYj4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Bicicleta Asustada', 7, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/JAAVmSpR#JdNzoRvYkBh6hhkerxnXLtblw4z0lplMJC-bHcLPA_4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Calendario de los Recuerdos', 8, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/9BJVAIwQ#CRkUv0KJVi7bgClp7LpYP0IzC8M7H1YQUT8j69TJCV8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura en el País de las Maravillas', 9, 'Lorem ipsum dolor sit amet',
        'https://www.yourupload.com/watch/dLkdr85MR4ku'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Kero y la Merienda', 10, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/kFBVRCyQ#5gYIbzWIyT3Mmytt7TmpXpBzeAW507Vxcd9EQQkzH18'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Ascensor', 11, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3CZWQAyD#VpkwXFJPPaLD-OuqWGG0xTBfBdUU9iNGufWYUniSk5Q'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y el Doble Problema', 12, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/bTA2SaqS#SsDGpwhkRmG2m4JDg8IxKvmjr75nx0TUPPIU68ZBssk'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Tomoyo y la Trampa de la Pelota', 13, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3XREQawB#YC20d2hb40zZAksBme6iiheQlD1sSAgqf53Sai0wAo8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y una Querida Amiga', 14, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/3WRwGIQJ#FD7hqpztf7L3fAZtCnvF6yrQVce2NV0IgIKIR_AKL8c'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, la Carta y los Regalos', 15, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/zPBmxQqR#FB80jnZQ-GCXgFLOgItXfV-ywHLBl3Ve03gnrAqPKIQ'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Extraña Predicción', 16, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7fQ0TKhB#8nLq4MG5ShKZMsECmbGosc5NDQrZm33_oCYGS9uc35A'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, la Piscina y la Ola Gigante', 17, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/ySRGTIKQ#meWtOD9AZR9cjip6497VkefKaMQ4SpAMmVymqgj6I1E'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y la Clase de Esquí', 18, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/iHBkDSZT#TSe_Y0rroiQPZOS4HyICXnbB1ZXR2RFTeob8T_qC6eY'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Yukito y el Poder de la Desaparición', 19, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/SbBAVaKA#xrmVvQh-CWMLVYOxE4WSEjUioBSJU4uTGjilN41Pcw0'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'La Persona que más le Gusta a Sakura', 20, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/yWR2WQBL#TLg-WQvPOt4NIXpSSTnjP4t_BA7-YcQwjGTiac-CQRs'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, Syaoran y el Templo Tsukimine', 21, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/eaZSXSAZ#uLmCHEwNipVfmiuGnCkGdh3tV1_WiuK3-CV7s5UiaEU'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura, el Pasado y el Amo Clow', 22, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/7OBk3YAb#0DYLrv56ox-Hr9MXrb6VU4yVhLGWxfo-DrL8UTGH2p8'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura se Encuentra con el Amo Clow', 23, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/WfYkhagS#wOxdSKqe7rKzR0DUvQu8n13NlNv8LJm1TO1uSxUcdy4'),
    ((SELECT seasonid from season where animeid = (select animeid from anime where name='Cardcaptor Sakura') AND num=3),
        'Sakura y sus Verdaderos Sentimientos', 24, 'Lorem ipsum dolor sit amet',
        'https://mega.nz/file/LCZ2FCjL#wuaa3dkrRUNizxecCF49stXnXOxwxtSb6lWptzbqnhw')
;